#!/usr/bin/env python3
"""
Build an embedded target image for the autonomous RAK4631 drone flasher.

Input: Nordic/Adafruit application-only OTA ZIP produced by the RAK4631 target build.
Output: C++ header containing:
  - Legacy DFU .dat init packet
  - LZ4-compressed application .bin
  - original/compressed sizes and target version label

The header is generated during CI and intentionally is not maintained by hand.
"""

import argparse
import json
import pathlib
import re
import zipfile

import lz4.block


def cpp_bytes(data: bytes, columns: int = 16) -> str:
    rows = []
    for i in range(0, len(data), columns):
        chunk = data[i:i + columns]
        rows.append("    " + ", ".join(f"0x{b:02X}" for b in chunk) + ",")
    return "\n".join(rows)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("ota_zip", type=pathlib.Path)
    parser.add_argument("output_header", type=pathlib.Path)
    args = parser.parse_args()

    with zipfile.ZipFile(args.ota_zip, "r") as zf:
        manifest = json.loads(zf.read("manifest.json"))
        app = manifest["manifest"]["application"]
        bin_name = app["bin_file"]
        dat_name = app["dat_file"]
        firmware = zf.read(bin_name)
        init_packet = zf.read(dat_name)

    compressed = lz4.block.compress(
        firmware,
        mode="high_compression",
        compression=12,
        store_size=False,
    )

    # Build-time verification: never embed a stream we cannot reconstruct exactly.
    check = lz4.block.decompress(compressed, uncompressed_size=len(firmware))
    if check != firmware:
        raise SystemExit("LZ4 verification failed")

    match = re.search(r"firmware-rak4631-([^/]+)\\.bin$", bin_name)
    version = match.group(1) if match else bin_name

    args.output_header.parent.mkdir(parents=True, exist_ok=True)
    args.output_header.write_text(
        """#pragma once
#include <stdint.h>
#include <stddef.h>

// AUTO-GENERATED by tools/build_drone_embedded_firmware.py.
// Do not edit by hand.

static constexpr char kEmbeddedDfuTargetVersion[] = \"%s\";
static constexpr uint32_t kEmbeddedDfuOriginalSize = %dUL;
static constexpr uint32_t kEmbeddedDfuCompressedSize = %dUL;
static constexpr uint16_t kEmbeddedDfuDatSize = %d;

static const uint8_t kEmbeddedDfuDat[] __attribute__((aligned(4))) = {
%s
};

static const uint8_t kEmbeddedDfuLz4[] __attribute__((aligned(4))) = {
%s
};
"""
        % (
            version,
            len(firmware),
            len(compressed),
            len(init_packet),
            cpp_bytes(init_packet),
            cpp_bytes(compressed),
        ),
        encoding="utf-8",
    )

    ratio = 100.0 * len(compressed) / len(firmware)
    print(f"Target: {version}")
    print(f"DAT: {len(init_packet)} bytes")
    print(f"BIN: {len(firmware)} bytes")
    print(f"LZ4: {len(compressed)} bytes ({ratio:.1f}% of original)")
    print(f"Header: {args.output_header}")


if __name__ == "__main__":
    main()
